import './globals.css'
import PageTitle from './components/PageTitle';
import styles from './styles/app.module.scss';
import Header from './components/Header';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body className="container">
        <PageTitle>TODO List</PageTitle>
        <div className={styles.app__wrapper}>
          <Header />
          {/* <AppContent /> */}
          {children}
          <footer>
            <small>© 2023 t4jet</small>
          </footer>
        </div>
      </body>
    </html>
  );
}
