import { Inter } from 'next/font/google'
import './globals.css'
import Link from "next/link";
import Header from './components/Header';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <head />
      <body className={inter.className}>
        <Header />
        {children}
        <footer>
          <small>© 2023 t4jet</small>
        </footer>
      </body>
    </html>
  );
}
