version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_HOST: goalrecord_mysql_1
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
    networks:
      - default

  
  mysql:
    image: mysql:8.0.27
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    networks:
      - default

  cli:
    image: mysql:8.0.27
    networks:
      - default
    command: mysql -hmysql -uuser -ppassword db

  frontend:
    build:
      context: ./frontend  # Dockerfileの場所を指定
      dockerfile: Dockerfile  # Dockerfileの名前を指定
    ports:
      - "3000:3000"

networks:
  default:
    driver: bridge
