version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3310
      DB_USER: username
      DB_PASS: password
      DB_NAME: database_name

  mysql:
    image: mysql:latest
    ports:
      - 3310:3310
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database_name

  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    # environment:
    #   BACKEND_API_URL: http://localhost:8080
