version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: user
      DB_PASS: password
      DB_NAME: db

  
  mysql:
    image: mysql:8.0.27
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
    networks:
      - default

  cli:
    image: mysql:8.0.27
    networks:
      - default
    command: mysql -hmysql -uuser -ppassword db

  frontend:
    build:
      context: ./frontend  # Dockerfileの場所を指定
      dockerfile: Dockerfile  # Dockerfileの名前を指定
    ports:
      - "3000:3000"
volumes:
  mysql_data:
networks:
  default:
    driver: bridge
